version: '3.8'
services:
  postgres-etl-dev:
    image: bitnami/postgresql:latest
    container_name: postgres-etl-dev
    ports:
      - '5434:5432'  # Mesma porta para facilitar
    environment:
      - POSTGRESQL_USERNAME=admin
      - POSTGRESQL_PASSWORD=admin123
      - POSTGRESQL_DATABASE=etl_man_os_db
      - POSTGRESQL_POSTGRES_PASSWORD=admin123
    volumes:
      - postgres_etl_dev_data:/bitnami/postgresql
      - ./migration-schema.sql:/docker-entrypoint-initdb.d/01-migration-schema.sql
    networks:
      - etl-dev-network
    restart: unless-stopped

networks:
  etl-dev-network:
    driver: bridge

volumes:
  postgres_etl_dev_data: