// apps/backend/src/migrations/1757010000000-CreateMultaCompletaTable.ts

import { MigrationInterface, QueryRunner, Table } from 'typeorm';

export class CreateMultaCompletaTable1757010000000 implements MigrationInterface {
  name = 'CreateMultaCompletaTable1757010000000';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.createTable(
      new Table({
        name: 'multas_completas',
        columns: [
          {
            name: 'numero_ai_multa',
            type: 'varchar',
            length: '50',
            isPrimary: true,
          },
          {
            name: 'descricao_infra',
            type: 'text',
            isNullable: true,
          },
          {
            name: 'prefixo_veic',
            type: 'varchar',
            length: '20',
            isNullable: true,
          },
          {
            name: 'cod_int_func',
            type: 'varchar',
            length: '50',
            isNullable: true,
          },
          {
            name: 'codigo_veic',
            type: 'varchar',
            length: '20',
            isNullable: true,
          },
          {
            name: 'codigo_infra',
            type: 'varchar',
            length: '20',
            isNullable: true,
          },
          {
            name: 'codigo_uf',
            type: 'varchar',
            length: '5',
            isNullable: true,
          },
          {
            name: 'cod_munic',
            type: 'varchar',
            length: '10',
            isNullable: true,
          },
          {
            name: 'codigo_org',
            type: 'varchar',
            length: '10',
            isNullable: true,
          },
          {
            name: 'data_emissao_multa',
            type: 'timestamp',
            isNullable: true,
          },
          {
            name: 'local_multa',
            type: 'text',
            isNullable: true,
          },
          {
            name: 'numero_local_multa',
            type: 'varchar',
            length: '50',
            isNullable: true,
          },
          {
            name: 'data_hora_multa',
            type: 'timestamp',
            isNullable: true,
          },
          {
            name: 'data_vecto_multa',
            type: 'date',
            isNullable: true,
          },
          {
            name: 'valor_multa',
            type: 'decimal',
            precision: 10,
            scale: 4,
            isNullable: true,
          },
          {
            name: 'total_parcelas_multa',
            type: 'integer',
            isNullable: true,
          },
          {
            name: 'valor_total_multa',
            type: 'decimal',
            precision: 10,
            scale: 4,
            isNullable: true,
          },
          {
            name: 'data_pagto_multa',
            type: 'date',
            isNullable: true,
          },
          {
            name: 'responsavel_multa',
            type: 'varchar',
            length: '10',
            isNullable: true,
          },
          {
            name: 'numero_recurso_multa',
            type: 'varchar',
            length: '50',
            isNullable: true,
          },
          {
            name: 'data_recurso_multa',
            type: 'date',
            isNullable: true,
          },
          {
            name: 'condicao_recurso_multa',
            type: 'varchar',
            length: '10',
            isNullable: true,
          },
          {
            name: 'valor_pago',
            type: 'decimal',
            precision: 10,
            scale: 4,
            isNullable: true,
          },
          {
            name: 'data_autorizado',
            type: 'date',
            isNullable: true,
          },
          {
            name: 'autorizado',
            type: 'varchar',
            length: '10',
            isNullable: true,
          },
          {
            name: 'decl_impresso_multa',
            type: 'varchar',
            length: '10',
            isNullable: true,
          },
          {
            name: 'documento',
            type: 'varchar',
            length: '50',
            isNullable: true,
          },
          {
            name: 'data_pagamento_prev',
            type: 'date',
            isNullable: true,
          },
          {
            name: 'vlr_acrescimo',
            type: 'decimal',
            precision: 10,
            scale: 4,
            isNullable: true,
          },
          {
            name: 'vlr_desconto',
            type: 'decimal',
            precision: 10,
            scale: 4,
            isNullable: true,
          },
          {
            name: 'valor_pagamento',
            type: 'decimal',
            precision: 10,
            scale: 4,
            isNullable: true,
          },
          {
            name: 'codigo_forn',
            type: 'varchar',
            length: '20',
            isNullable: true,
          },
          {
            name: 'cod_lanca',
            type: 'varchar',
            length: '20',
            isNullable: true,
          },
          {
            name: 'id_prest2',
            type: 'varchar',
            length: '20',
            isNullable: true,
          },
          {
            name: 'cod_doc_tocpg',
            type: 'varchar',
            length: '20',
            isNullable: true,
          },
          {
            name: 'cod_int_proaut',
            type: 'varchar',
            length: '20',
            isNullable: true,
          },
          {
            name: 'observacao',
            type: 'text',
            isNullable: true,
          },
          {
            name: 'data_limite_condutor',
            type: 'date',
            isNullable: true,
          },
          {
            name: 'numero_recurso_multa2',
            type: 'varchar',
            length: '50',
            isNullable: true,
          },
          {
            name: 'data_recurso_multa2',
            type: 'date',
            isNullable: true,
          },
          {
            name: 'condicao_recurso_multa2',
            type: 'varchar',
            length: '10',
            isNullable: true,
          },
          {
            name: 'cod_motivo_notificacao',
            type: 'varchar',
            length: '10',
            isNullable: true,
          },
          {
            name: 'cod_area_competencia',
            type: 'varchar',
            length: '10',
            isNullable: true,
          },
          {
            name: 'cod_responsavel_notificacao',
            type: 'varchar',
            length: '10',
            isNullable: true,
          },
          {
            name: 'cod_agente_autuador',
            type: 'varchar',
            length: '20',
            isNullable: true,
          },
          {
            name: 'cod_int_linha',
            type: 'varchar',
            length: '20',
            isNullable: true,
          },
          {
            name: 'codlinha',
            type: 'varchar',
            length: '20',
            isNullable: true,
          },
          {
            name: 'numero_recurso_multa3',
            type: 'varchar',
            length: '50',
            isNullable: true,
          },
          {
            name: 'data_recurso_multa3',
            type: 'date',
            isNullable: true,
          },
          {
            name: 'condicao_recurso_multa3',
            type: 'varchar',
            length: '10',
            isNullable: true,
          },
          {
            name: 'flg_prim_parcela_paga',
            type: 'varchar',
            length: '5',
            isNullable: true,
          },
          {
            name: 'entrada_vencimento',
            type: 'date',
            isNullable: true,
          },
          {
            name: 'entrada_pagamento',
            type: 'date',
            isNullable: true,
          },
          {
            name: 'auto_de_infracao',
            type: 'varchar',
            length: '50',
            isNullable: true,
          },
          {
            name: 'auto_de_infracao_emissao',
            type: 'date',
            isNullable: true,
          },
          {
            name: 'auto_de_infracao_recebimento',
            type: 'date',
            isNullable: true,
          },
          {
            name: 'auto_de_infracao_considerado',
            type: 'date',
            isNullable: true,
          },
          {
            name: 'auto_de_infracao_valor_do_doc',
            type: 'decimal',
            precision: 10,
            scale: 2,
            isNullable: true,
          },
          {
            name: 'auto_de_infracao_valor_considerado',
            type: 'decimal',
            precision: 10,
            scale: 2,
            isNullable: true,
          },
          // Notificações
          {
            name: 'notificacao1',
            type: 'varchar',
            length: '50',
            isNullable: true,
          },
          {
            name: 'notificacao1_emissao',
            type: 'date',
            isNullable: true,
          },
          {
            name: 'notificacao1_recebimento',
            type: 'date',
            isNullable: true,
          },
          {
            name: 'notificacao1_considerado',
            type: 'date',
            isNullable: true,
          },
          {
            name: 'notificacao1_valor_do_doc',
            type: 'decimal',
            precision: 10,
            scale: 2,
            isNullable: true,
          },
          {
            name: 'notificacao1_valor_considerado',
            type: 'decimal',
            precision: 10,
            scale: 2,
            isNullable: true,
          },
          {
            name: 'notificacao2',
            type: 'varchar',
            length: '50',
            isNullable: true,
          },
          {
            name: 'notificacao2_emissao',
            type: 'date',
            isNullable: true,
          },
          {
            name: 'notificacao2_recebimento',
            type: 'date',
            isNullable: true,
          },
          {
            name: 'notificacao2_considerado',
            type: 'date',
            isNullable: true,
          },
          {
            name: 'notificacao2_valor_do_doc',
            type: 'decimal',
            precision: 10,
            scale: 2,
            isNullable: true,
          },
          {
            name: 'notificacao2_valor_considerado',
            type: 'decimal',
            precision: 10,
            scale: 2,
            isNullable: true,
          },
          {
            name: 'notificacao3',
            type: 'varchar',
            length: '50',
            isNullable: true,
          },
          {
            name: 'notificacao3_emissao',
            type: 'date',
            isNullable: true,
          },
          {
            name: 'notificacao3_recebimento',
            type: 'date',
            isNullable: true,
          },
          {
            name: 'notificacao3_considerado',
            type: 'date',
            isNullable: true,
          },
          {
            name: 'notificacao3_valor_do_doc',
            type: 'decimal',
            precision: 10,
            scale: 2,
            isNullable: true,
          },
          {
            name: 'notificacao3_valor_considerado',
            type: 'decimal',
            precision: 10,
            scale: 2,
            isNullable: true,
          },
          // Campos adicionais
          {
            name: 'valor_atualizado',
            type: 'decimal',
            precision: 10,
            scale: 2,
            isNullable: true,
          },
          {
            name: 'pgto_intemp_data',
            type: 'date',
            isNullable: true,
          },
          {
            name: 'pgto_intemp_valor',
            type: 'decimal',
            precision: 10,
            scale: 2,
            isNullable: true,
          },
          {
            name: 'dep_jud_data',
            type: 'date',
            isNullable: true,
          },
          {
            name: 'dep_jud_valor',
            type: 'decimal',
            precision: 10,
            scale: 2,
            isNullable: true,
          },
          {
            name: 'dep_jud_dt_recup',
            type: 'date',
            isNullable: true,
          },
          {
            name: 'dep_jud_vlr_recup',
            type: 'decimal',
            precision: 10,
            scale: 2,
            isNullable: true,
          },
          {
            name: 'numero_processo',
            type: 'varchar',
            length: '100',
            isNullable: true,
          },
          // Parcelas
          {
            name: 'parc_valor',
            type: 'decimal',
            precision: 10,
            scale: 2,
            isNullable: true,
          },
          {
            name: 'parc_total_parcelas',
            type: 'integer',
            isNullable: true,
          },
          {
            name: 'parc_valor_parcelas',
            type: 'decimal',
            precision: 10,
            scale: 2,
            isNullable: true,
          },
          {
            name: 'ent_vencimento',
            type: 'date',
            isNullable: true,
          },
          {
            name: 'ent_pagamento',
            type: 'date',
            isNullable: true,
          },
          {
            name: 'ent_valor',
            type: 'decimal',
            precision: 10,
            scale: 2,
            isNullable: true,
          },
          {
            name: 'par_vencimento',
            type: 'date',
            isNullable: true,
          },
          {
            name: 'par_pagamento',
            type: 'date',
            isNullable: true,
          },
          {
            name: 'par_valor',
            type: 'decimal',
            precision: 10,
            scale: 2,
            isNullable: true,
          },
          {
            name: 'ult_par_vencimento',
            type: 'date',
            isNullable: true,
          },
          {
            name: 'ult_par_pagamento',
            type: 'date',
            isNullable: true,
          },
          {
            name: 'ult_par_valor',
            type: 'decimal',
            precision: 10,
            scale: 2,
            isNullable: true,
          },
          {
            name: 'total_pago',
            type: 'decimal',
            precision: 10,
            scale: 2,
            isNullable: true,
          },
          {
            name: 'recuso',
            type: 'varchar',
            length: '10',
            isNullable: true,
          },
          {
            name: 'anistia',
            type: 'varchar',
            length: '10',
            isNullable: true,
          },
          // Instâncias
          {
            name: 'instancia_envio1',
            type: 'date',
            isNullable: true,
          },
          {
            name: 'instancia_publicacao_do1',
            type: 'date',
            isNullable: true,
          },
          {
            name: 'instancia_envio2',
            type: 'date',
            isNullable: true,
          },
          {
            name: 'instancia_publicacao_do2',
            type: 'date',
            isNullable: true,
          },
          {
            name: 'instancia_envio3',
            type: 'date',
            isNullable: true,
          },
          {
            name: 'instancia_publicacao_do3',
            type: 'date',
            isNullable: true,
          },
          {
            name: 'integrou_por_vencimento',
            type: 'varchar',
            length: '10',
            isNullable: true,
          },
          {
            name: 'valor_julgado',
            type: 'decimal',
            precision: 10,
            scale: 2,
            isNullable: true,
          },
          {
            name: 'codigo_recuperacao',
            type: 'varchar',
            length: '20',
            isNullable: true,
          },
          {
            name: 'n_processo_notificacao',
            type: 'varchar',
            length: '100',
            isNullable: true,
          },
          {
            name: 'auto_de_infracao_prazo',
            type: 'varchar',
            length: '20',
            isNullable: true,
          },
          {
            name: 'notificacao1_prazo',
            type: 'varchar',
            length: '20',
            isNullable: true,
          },
          {
            name: 'notificacao2_prazo',
            type: 'varchar',
            length: '20',
            isNullable: true,
          },
          {
            name: 'notificacao3_prazo',
            type: 'varchar',
            length: '20',
            isNullable: true,
          },
          {
            name: 'pgto_intemp_venc',
            type: 'date',
            isNullable: true,
          },
          {
            name: 'dep_jud_venc',
            type: 'date',
            isNullable: true,
          },
          {
            name: 'cod_causa_principal',
            type: 'varchar',
            length: '20',
            isNullable: true,
          },
          {
            name: 'env_penalidade',
            type: 'varchar',
            length: '20',
            isNullable: true,
          },
          {
            name: 'rev_penalidade',
            type: 'varchar',
            length: '20',
            isNullable: true,
          },
          {
            name: 'obs_notificacao',
            type: 'text',
            isNullable: true,
          },
          {
            name: 'recuperada',
            type: 'varchar',
            length: '10',
            isNullable: true,
          },
          {
            name: 'palavra_chave',
            type: 'varchar',
            length: '100',
            isNullable: true,
          },
          {
            name: 'tratamento_multa',
            type: 'varchar',
            length: '20',
            isNullable: true,
          },
          {
            name: 'importacao_ok',
            type: 'varchar',
            length: '10',
            isNullable: true,
          },
          {
            name: 'tipo_de_trecho',
            type: 'varchar',
            length: '20',
            isNullable: true,
          },
          {
            name: 'reembolsavel',
            type: 'varchar',
            length: '10',
            isNullable: true,
          },
          {
            name: 'km_local_multa',
            type: 'varchar',
            length: '20',
            isNullable: true,
          },
          {
            name: 'metros_local_multa',
            type: 'varchar',
            length: '20',
            isNullable: true,
          },
          {
            name: 'sentido_local_multa',
            type: 'varchar',
            length: '50',
            isNullable: true,
          },
          {
            name: 'bairro_local_multa',
            type: 'varchar',
            length: '100',
            isNullable: true,
          },
          {
            name: 'observacao_real_motivo',
            type: 'text',
            isNullable: true,
          },
          {
            name: 'tipo_tratamento_multa',
            type: 'varchar',
            length: '20',
            isNullable: true,
          },
          {
            name: 'executor',
            type: 'varchar',
            length: '100',
            isNullable: true,
          },
          {
            name: 'executor_cnpj_cpf',
            type: 'varchar',
            length: '20',
            isNullable: true,
          },
          {
            name: 'ult_alteracao',
            type: 'timestamp',
            isNullable: true,
          },
          {
            name: 'ocorrencia',
            type: 'varchar',
            length: '50',
            isNullable: true,
          },
          {
            name: 'codigo_ressarc',
            type: 'varchar',
            length: '20',
            isNullable: true,
          },
          {
            name: 'flg_smartec',
            type: 'varchar',
            length: '10',
            isNullable: true,
          },
          {
            name: 'data_imp_smartec',
            type: 'date',
            isNullable: true,
          },
          {
            name: 'url_formulario',
            type: 'text',
            isNullable: true,
          },
          {
            name: 'url_boleto',
            type: 'text',
            isNullable: true,
          },
          {
            name: 'flg_smartec_multa',
            type: 'varchar',
            length: '10',
            isNullable: true,
          },
          {
            name: 'reincidencia',
            type: 'varchar',
            length: '10',
            isNullable: true,
          },
          {
            name: 'pontuacao_infracao',
            type: 'integer',
            isNullable: true,
          },
          {
            name: 'grupo_infracao',
            type: 'varchar',
            length: '50',
            isNullable: true,
          },
          {
            name: 'cod_org_original',
            type: 'varchar',
            length: '20',
            isNullable: true,
          },
          {
            name: 'ait_original',
            type: 'varchar',
            length: '50',
            isNullable: true,
          },
          // Dados do agente
          {
            name: 'agente_codigo',
            type: 'varchar',
            length: '20',
            isNullable: true,
          },
          {
            name: 'agente_descricao',
            type: 'varchar',
            length: '200',
            isNullable: true,
          },
          {
            name: 'agente_matricula_fiscal',
            type: 'varchar',
            length: '20',
            isNullable: true,
          },
          // Campos de controle
          {
            name: 'codigo_empresa',
            type: 'integer',
            default: 4,
          },
          {
            name: 'created_at',
            type: 'timestamp',
            default: 'CURRENT_TIMESTAMP',
          },
          {
            name: 'updated_at',
            type: 'timestamp',
            default: 'CURRENT_TIMESTAMP',
          },
          {
            name: 'sincronizado_em',
            type: 'timestamp',
            default: 'CURRENT_TIMESTAMP',
          },
        ],
        indices: [
          {
            name: 'IDX_multas_completas_data_emissao',
            columnNames: ['data_emissao_multa', 'codigo_empresa'],
          },
          {
            name: 'IDX_multas_completas_prefixo',
            columnNames: ['prefixo_veic'],
          },
          {
            name: 'IDX_multas_completas_codigo_veic',
            columnNames: ['codigo_veic'],
          },
          {
            name: 'IDX_multas_completas_codigo_infra',
            columnNames: ['codigo_infra'],
          },
          {
            name: 'IDX_multas_completas_agente',
            columnNames: ['agente_codigo'],
          },
          {
            name: 'IDX_multas_completas_sincronizado',
            columnNames: ['sincronizado_em'],
          },
          {
            name: 'IDX_multas_completas_data_vecto',
            columnNames: ['data_vecto_multa'],
          },
          {
            name: 'IDX_multas_completas_data_pagto',
            columnNames: ['data_pagto_multa'],
          },
        ],
      }),
      true,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.dropTable('multas_completas');
  }
}